### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sh1va73** [BullsEye0/ghost_eye#1]
Great tool, but when i try DNS Lookup I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/dig", line 5, in <module>
    from dig.cmdline import main
  File "/usr/local/lib/python3.7/dist-packages/dig/cmdline.py", line 31, in <module>
    from dig.translate import Translator,Speaker
  File "/usr/local/lib/python3.7/dist-packages/dig/translate.py", line 4, in <module>
    from translate_api import TranslateService,TTSService
ModuleNotFoundError: No module named 'translate_api'

**Comment by sh1va73** [comment]
For those experiencing the same issue I have solved with reinstalling dnsutils.
